name: End-to-end testing

# E2E tests can be invoked manually.
# They are invoked automatically when a new tag (version) is pushed however.
# TODO: move this to when a new release is made?
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Invoke tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER: ${{ secrets.SERVER }}
          DATASTORE_SERVER: ${{ secrets.DATASTORE_SERVER }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          set -eu
          export SERVER API_KEY
          pwd
          cd e2e
          ./up.sh
          ./polar-test.sh
          ./down.sh
